person:
  lastName: 张三
  age: 25
  isBoss: false
  birth: 2017/12/12
  maps: {key1: value1,key2: value2}
  lists:
    - 雷军
    - 乔布斯
    - 马云
  dog:
    name: milly
    age: 2
    
user:  
  user-name: 'zhangsan'  
  gender: 2  
  
environments:
    dev:
        url: http://dev.bar.com
        name: Developer Setup
    prod:
        url: http://foo.bar.com
        name: My Cool App
  
  
  